version: '3'
services:
  # service-eureka-server
  eureka:
    restart: on-failure:5
    build:
      context: ../service-eureka-server
      dockerfile: Dockerfile-compose
    command: mvn clean spring-boot:run -Dspring.profiles.active=compose
    volumes:
      - /tmp/m2:/root/.m2:rw
    ports:
      - 8761:8761
    expose:
      - 8761
    networks:
      - bridge-network
  # service-config-server
  config:
    restart: on-failure:5
    build:
      context: ../service-config-server
      dockerfile: Dockerfile-compose
    depends_on:
      - eureka
    command: mvn clean spring-boot:run -Dspring.profiles.active=compose
    volumes:
      - /tmp/m2:/root/.m2:rw
    ports:
      - 33001:33001
    expose:
      - 33001
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge