version: '3'
services:
  #service-rss-reader
  rss-reader:
    restart: on-failure:5
    image: registry.gitlab.com/dotterbear/service-rss-reader
    depends_on:
      - rss-reader-mongo
    volumes:
      - /tmp/m2:/root/.m2:rw
    environment:
      MONGODB_HOST: ${BRIDGE_NETWORK}
    ports:
      - 8762:8762
    expose:
      - 8762
    networks:
      - bridge-network
  rss-reader-mongo:
    restart: always
    image: registry.gitlab.com/dotterbear/mongodb-docker-template/service/service-rss-reader
    ports:
      - 33002:27017
    expose:
      - 33002
    networks:
      - bridge-network
  # service-jobad-reader
  jobad-reader:
    restart: on-failure:5
    image: registry.gitlab.com/dotterbear/service-jobad-reader
    depends_on:
      - jodab-reader-mongo
    volumes:
      - /tmp/m2:/root/.m2:rw
    environment:
      MONGODB_HOST: ${BRIDGE_NETWORK}
    ports:
      - 8765:8765
    expose:
      - 8765
    networks:
      - bridge-network
  jodab-reader-mongo:
    restart: always
    image: registry.gitlab.com/dotterbear/mongodb-docker-template/service/service-rss-reader
    ports:
      - 37017:27017
    expose:
      - 37017
    networks:
      - bridge-network
  # service-eureka-scheduler
  eureka-scheduler:
    restart: on-failure:5
    image: registry.gitlab.com/dotterbear/service-eureka-scheduler
    depends_on:
      - rss-reader
      - jobad-reader
    volumes:
      - /tmp/m2:/root/.m2:rw
    ports:
      - 8763:8763
    expose:
      - 8763
    networks:
      - bridge-network
  # service-zuul-server
  zuul-server:
    restart: on-failure:5
    image: registry.gitlab.com/dotterbear/service-zuul-server
    volumes:
      - /tmp/m2:/root/.m2:rw
    ports:
      - 8767:8766
    expose:
      - 8767
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge