version: '3'
services:
  #service-rss-reader
  rss-reader:
    restart: on-failure:5
    build:
      context: ../service-rss-reader
      dockerfile: Dockerfile-compose
    depends_on:
      - rss-reader-mongo
    command: mvn clean spring-boot:run -Dspring.profiles.active=compose
    volumes:
      - /tmp/m2:/root/.m2:rw
    environment:
      MONGODB_HOST: ${BRIDGE_NETWORK}
    ports:
      - 8762:8762
    expose:
      - 8762
    networks:
      - bridge-network
  rss-reader-mongo:
    restart: always
    build:
      context: ../mongodb-docker-template/service-rss-reader
      dockerfile: Dockerfile-compose
    ports:
      - 33002:27017
    expose:
      - 33002
    networks:
      - bridge-network
  # service-jobad-reader
  jobad-reader:
    restart: on-failure:5
    build:
      context: ../service-jobad-reader
      dockerfile: Dockerfile-compose
    depends_on:
      - jodab-reader-mongo
    command: mvn clean spring-boot:run -Dspring.profiles.active=compose
    volumes:
      - /tmp/m2:/root/.m2:rw
    environment:
      MONGODB_HOST: ${BRIDGE_NETWORK}
    ports:
      - 8765:8765
    expose:
      - 8765
    networks:
      - bridge-network
  jodab-reader-mongo:
    restart: always
    build:
      context: ../mongodb-docker-template/service-jobad-reader
      dockerfile: Dockerfile-compose
    ports:
      - 37017:27017
    expose:
      - 37017
    networks:
      - bridge-network
  # service-eureka-scheduler
  eureka-scheduler:
    restart: on-failure:5
    build:
      context: ../service-eureka-scheduler
      dockerfile: Dockerfile-compose
    depends_on:
      - rss-reader
      - jobad-reader
    command: mvn clean spring-boot:run -Dspring.profiles.active=compose
    volumes:
      - /tmp/m2:/root/.m2:rw
    ports:
      - 8763:8763
    expose:
      - 8763
    networks:
      - bridge-network
  # service-zuul-server
  zuul-server:
    restart: on-failure:5
    build:
      context: ../service-zuul-server
      dockerfile: Dockerfile-compose
    command: mvn clean spring-boot:run -Dspring.profiles.active=compose
    volumes:
      - /tmp/m2:/root/.m2:rw
    ports:
      - 8767:8766
    expose:
      - 8767
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge